### ISSUE TITLE
Can not find Generating test/GrowCutHeaderTest1.cxx

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITKGrowCut#16]
When building the `ITKGrowCut` project, a bug is reported if `BUILD_TESTING` is `ON`:

```
can not find  Generating test/GrowCutHeaderTest1.cxx
```

**Comment by dzenanz** [comment]
I think that this frequently fails on Windows. Doing another build or two, gets it building eventually.

**Comment by zhang-qiang-github** [comment]
This bug is caused by not successfully download some files. I will build it more times.
