### ISSUE TITLE
How to build ITKGrowCut?

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITKGrowCut#17]
Since `ITKGrowCut` is a remote module for ITK, should I put `ITKGrowCut` into to `ITK/Modules/ThirdParty` or implement a `GrowCut.remote.cmake` by myself?

I have directly build `ITKGrowCut`, but it failed to find `GrowCut` in `CMake`:

```
find_package(GrowCut)
or
find_package(ITKGrowCut)
```

**Comment by dzenanz** [comment]
When configuring/building ITK, turn on `Module_GrowCut`. Then just use ITK. Alternatively, `find_package(ITK COMPONENTS GrowCut)`.

**Comment by dzenanz** [comment]
Also take a look at [this forum discussion](https://discourse.itk.org/t/find-all-available-modules-from-groupio/351).

**Comment by zhang-qiang-github** [comment]
But `ITK` do not have `Module_GrowCut` entry. Even I add this entry and build itk, it do not build `GrowCut` project.

**Comment by dzenanz** [comment]
GrowCut was added in [July 2021](https://github.com/InsightSoftwareConsortium/ITK/pull/2642). You need to use master branch or a pre-release (e.g. v5.3RC3).

**Comment by zhang-qiang-github** [comment]
Thank you for your kindly reply~~~
