### ISSUE TITLE
How to accelerate ITKGrowCut

### ISSUE THREAD

**Issue by AeBoPi** [InsightSoftwareConsortium/ITKGrowCut#19]
Hi, I used ITKGrowCut test code with my data, and
 it worked, but very slow. My data_size is 512x512x785, and i need take 3-4 minutes to process it. May i ask you how to accelerate it? 

my test code is:
```
#include <iostream>
#include <string>
#include "itkFastGrowCut.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"


int main(int argc, char* argv[])
{
	const char* inputImage = "E:\\HCM\\DATASET\\itkgrwocut\\image.nii.gz";
	const char* seedsImage = "E:\\HCM\\DATASET\\itkgrwocut\\seed.nii.gz";
	const char* noisyLabels = "E:\\HCM\\DATASET\\itkgrwocut\\label.nii.gz";

	constexpr unsigned int Dimension = 3;
	using PixelType = short;
	using ImageType = itk::Image<PixelType, Dimension>;
	using LabelType = itk::Image<unsigned char, Dimension>;

	using FGCType = itk::FastGrowCut<ImageType, LabelType>;
	FGCType::Pointer fgcFilter = FGCType::New();
	// Read the images
	typedef itk::ImageFileReader<ImageType> ReaderType;
	ReaderType::Pointer reader = ReaderType::New();
	reader->SetFileName(inputImage);
	reader->Update();
	ImageType::Pointer image = reader->GetOutput();
	typedef itk::ImageFileReader<LabelType> ReaderType2;
	ReaderType2::Pointer reader2 = ReaderType2::New();
	reader2->SetFileName(seedsImage);
	reader2->Update();
	LabelType::Pointer seeds = reader2->GetOutput();

	// Filter the original, possibly noisy image
	fgcFilter->SetInput(image);
	fgcFilter->SetSeedImage(seeds);
	fgcFilter->Update();

	using WriterType = itk::ImageFileWriter<LabelType>;
	WriterType::Pointer writer = WriterType::New();
	writer->SetInput(fgcFilter->GetOutput());
	writer->SetFileName(noisyLabels);
	writer->Update();
	std::cout << "Test finished." << std::endl;
	return EXIT_SUCCESS;
}
```

the inputimage and seed are： 

![1691034070144](https://github.com/InsightSoftwareConsortium/ITKGrowCut/assets/109503402/0ea9de52-e189-4dbd-8bce-712eb8e3c26b)
![1691034127358](https://github.com/InsightSoftwareConsortium/ITKGrowCut/assets/109503402/a31d1a67-ddf7-402c-be54-d6f9cf0f4b65)

**Comment by dzenanz** [comment]
You could downsample your data. But I assume you knew that already. You could also crop the image to just the interesting part. I doubt you can do much more than that. 3-4 minutes for such a large image sounds reasonable.

**Comment by AeBoPi** [comment]
ok, thank you for your suggestions. You give me a new way to solve it —— deal with data.  I'm wonder is there a way to accelerate the progress from code? I use slicer process this data with the same seed image, it takes about 1minute, does it use some magic? 😂

**Comment by dzenanz** [comment]
Slicer probably does automatic cropping of the image to just the part around the seeds.

**Comment by AeBoPi** [comment]
> Slicer probably does automatic cropping of the image to just the part around the seeds.

That sounds reasonable, thanks again!

**Comment by AeBoPi** [comment]
> 



> > Slicer probably does automatic cropping of the image to just the part around the seeds.
> 
> That sounds reasonable, thanks again!

I will try to crop the image tomorrow, and update progression.

**Comment by AeBoPi** [comment]
> > 
> 
> > > Slicer probably does automatic cropping of the image to just the part around the seeds.
> > 
> > 
> > That sounds reasonable, thanks again!
> 
> I will try to crop the image tomorrow, and update progression.

I cropped the image to the ROI, and the process time reduce to 1 minute, it's really a good idea!
