### ISSUE TITLE
Update the code to mirror the one in Slicer

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKGrowCut#3]
The code [in Slicer](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Segmentations/Logic/vtkImageGrowCutSegment.cxx) has been refactored and improved, compared to the [original one](https://github.com/ljzhu/FastGrowCut) from which current implementation is derived.

**Comment by lassoan** [comment]
In Slicer, we significantly improved speed, robustness, memory usage and added a very important feature: masking (so that you can restrict segmentation with a binary mask), and an occasionally useful feature: seed locality (adding a distance penalty term to make segmentation results more consistent in images that contain very-low-noise regions).

**Comment by junqiangchen** [comment]
> In Slicer, we significantly improved speed, robustness, memory usage and added a very important feature: masking (so that you can restrict segmentation with a binary mask), and an occasionally useful feature: seed locality (adding a distance penalty term to make segmentation results more consistent in images that contain very-low-noise regions).

hi,@lassoan,i want use vtkImageGrowCutSegment.h in my project, here is program
`std::string inputimagepath = "D:\\ct3dimage.nii.gz";
	ipc::Short3dImageType::Pointer inputimage = ipc::Short3dImageType::New();
	ipc::FileRead(inputimagepath, inputimage);

	std::string inputseedspath = "D:\\seedsimagesitk.nii.gz";
	ipc::Short3dImageType::Pointer inputseeds = ipc::Short3dImageType::New();
	ipc::FileRead(inputseedspath, inputseeds);

	std::string inputmaskpath = "D:\\binary_image_step1.nii.gz";
	ipc::Short3dImageType::Pointer inputmask = ipc::Short3dImageType::New();
	ipc::FileRead(inputmaskpath, inputmask);
	int dims[3];
	vtkSmartPointer<vtkImageData> inputimagevtk = vtkSmartPointer<vtkImageData>::New();
	ipc::ConvertITKImage2VTKImage(inputimage, inputimagevtk);
	vtkSmartPointer<vtkImageData> inputseedsvtk = vtkSmartPointer<vtkImageData>::New();
	ipc::ConvertITKImage2VTKImage(inputseeds, inputseedsvtk);
	vtkSmartPointer<vtkImageData> inputmaskvtk = vtkSmartPointer<vtkImageData>::New();
	ipc::ConvertITKImage2VTKImage(inputmask, inputmaskvtk);
	vtkSmartPointer<vtkImageGrowCutSegment> growcutsegment = vtkSmartPointer<vtkImageGrowCutSegment>::New();
	growcutsegment->SetIntensityVolume(inputimagevtk);
	inputimagevtk->GetDimensions(dims);
	std::cout << dims[0] << "," << dims[1] << "," << dims[2] << std::endl;
	growcutsegment->SetSeedLabelVolume(inputseedsvtk);
	inputseedsvtk->GetDimensions(dims);
	std::cout << dims[0] << "," << dims[1] << "," << dims[2] << std::endl;
	growcutsegment->SetMaskVolume(inputmaskvtk);
	inputmaskvtk->GetDimensions(dims);
	std::cout << dims[0] << "," << dims[1] << "," << dims[2] << std::endl;
	growcutsegment->Update();

	vtkSmartPointer<vtkImageData> outputmaskvtk = vtkSmartPointer<vtkImageData>::New();
	vtkSmartPointer<vtkImageCast> imagecast = vtkSmartPointer<vtkImageCast>::New();
	imagecast->SetInputData(growcutsegment->GetOutput());
	imagecast->SetOutputScalarTypeToShort();
	imagecast->Update();
	outputmaskvtk = imagecast->GetOutput();
	growcutsegment->GetOutput()->GetDimensions(dims);
	std::cout << dims[0] << "," << dims[1] << "," << dims[2] << std::endl;
	ipc::Short3dImageType::Pointer outputmask = ipc::Short3dImageType::New();
	ipc::ConvertVTKImage2ITKImage(outputmaskvtk, outputmask);
	ipc::FileWrite("growcutsegmenation.nii.gz", outputmask);`
![捕获](https://user-images.githubusercontent.com/28638716/125410800-d8dd4200-e3ef-11eb-8c84-344e1823f965.PNG)
![捕获2](https://user-images.githubusercontent.com/28638716/125410836-e1ce1380-e3ef-11eb-8bd3-44258a95b117.PNG)
first image is  ct3dimage and seedsmask,another is mask image.
i run the progarm,get null result.
can you help me how to get right result,or share some c++ example?

thank you
chenjunqiang

**Comment by dzenanz** [comment]
If you are working with ITK images, you could use this module. You could look at the test to see how to use it, in particular these lines:
https://github.com/InsightSoftwareConsortium/ITKGrowCut/blob/6c4a4a35ebf605cd20cfc0a1c7d54a5e56cb4a6a/test/itkFastGrowCutTest.cxx#L72-L93

**Comment by dzenanz** [comment]
Also, this filter needs at least 2 labels, one for the object and one for the background.

**Comment by lassoan** [comment]
If you want to have the improved filter with an ITK interface then I would recommend to port the improvements from Slicer's implementation to this ITK remote module and send a pull request to pass on the maintenance workload to the community.

If you implement a medical imaging application then the best choice is probably simply to use/customize/extend 3D Slicer instead of struggle other limited custom application frameworks. Note that ITK-Snap comes with a GPL license, so you are not allowed to use it as a basis of custom closed-source/commercial application.

**Comment by dzenanz** [comment]
> the improved filter with an ITK interface

Yes, this is the goal. [PR 2642](https://github.com/InsightSoftwareConsortium/ITK/pull/2642) adds the current progress (un-improved filter with ITK interface) to ITK for easy building.

**Comment by lassoan** [comment]
> If you want to have the improved filter with an ITK interface then I would recommend to port the improvements from Slicer's implementation to this ITK remote module and send a pull request to pass on the maintenance workload to the community.

I meant this for @junqiangchen.

@dzenanz I know that you plan to implement this, but if @junqiangchen wants to get this sooner and has time to start working on it then that could help you.

**Comment by junqiangchen** [comment]
> If you are working with ITK images, you could use this module. You could look at the test to see how to use it, in particular these lines:
> https://github.com/InsightSoftwareConsortium/ITKGrowCut/blob/6c4a4a35ebf605cd20cfc0a1c7d54a5e56cb4a6a/test/itkFastGrowCutTest.cxx#L72-L93

@dzenanz thank you,i will try

**Comment by dzenanz** [comment]
Done in 777ba0e4e1aec627ad2f70cdbc24629b01ccad0b.
