### ISSUE TITLE
how to use ITKGrowCut

### ISSUE THREAD

**Issue by junqiangchen** [InsightSoftwareConsortium/ITKGrowCut#5]
hi,i want use ITKGrowCut in my project,i modify the test code,the program like this:
```cpp
#include <iostream>
#include "itkFastGrowCut.h"

#include "itkCommand.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkMedianImageFilter.h"
#include "itkTestingMacros.h"


int main(int argc, char* argv[])
{
	const char* inputImage = "D:\\roi_image_sitk.nii.gz";
	const char* seedsImage = "D:\\seedsimagesitk.nii.gz";
	const char* noisyLabels = "growcut.nii.gz";

	constexpr unsigned int Dimension = 3;
	using PixelType = short;
	using ImageType = itk::Image<PixelType, Dimension>;
	using LabelType = itk::Image<unsigned char, Dimension>;

	using FGCType = itk::FastGrowCut<ImageType, LabelType>;
	FGCType::Pointer fgcFilter = FGCType::New();
	// Read the images
	typedef itk::ImageFileReader<ImageType> ReaderType;
	ReaderType::Pointer reader = ReaderType::New();
	reader->SetFileName(inputImage);
	reader->Update();
	ImageType::Pointer image = reader->GetOutput();
	typedef itk::ImageFileReader<LabelType> ReaderType2;
	ReaderType2::Pointer reader2 = ReaderType2::New();
	reader2->SetFileName(seedsImage);
	reader2->Update();
	LabelType::Pointer seeds = reader2->GetOutput();

	// Filter the original, possibly noisy image
	fgcFilter->SetInput(image);
	fgcFilter->SetSeedImage(seeds);
	fgcFilter->Update();

	using WriterType = itk::ImageFileWriter<LabelType>;
	WriterType::Pointer writer = WriterType::New();
	writer->SetInput(fgcFilter->GetOutput());
	writer->SetFileName(noisyLabels);
	writer->Update();
	std::cout << "Test finished." << std::endl;
	return EXIT_SUCCESS;
}
```
image and seed mask image is this:
![捕获](https://user-images.githubusercontent.com/28638716/125410045-1392aa80-e3ef-11eb-8f7d-ede7f7998525.PNG)
the program can get result,but the result is same with seedsimagesitk,don't have any binary mask image.
maybe some wrong with my input image and seed mask,can you share example how to use it?

thank you
chenjunqiang

**Comment by dzenanz** [comment]
You can find example test inputs and seeds here:
https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/6081794d2fa25629b90b3687

You can find correspondence between inputs, seeds and outputs from this file:
https://github.com/InsightSoftwareConsortium/ITKGrowCut/blob/master/test/CMakeLists.txt

I think that your main issues is a need for at least 2 seeds of different labels.

**Comment by junqiangchen** [comment]
> You can find example test inputs and seeds here:
> https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/6081794d2fa25629b90b3687
> 
> You can find correspondence between inputs, seeds and outputs from this file:
> https://github.com/InsightSoftwareConsortium/ITKGrowCut/blob/master/test/CMakeLists.txt
> 
> I think that your main issues is a need for at least 2 seeds of different labels.

@dzenanz  thank you,i will try again
