### ISSUE TITLE
Can not successfully build ITKGrowCut

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITKGrowCut#6]
I want to use `ITKGrowCut` in my project, but there are some trouble to build it. 

Firstly, I can successfully compile it. But when I include the `itkFastGrowCut.h`, a bug is reported:

```
1. can not open "itkPrintHelper.h"
2. missing type specifier- int assumed. Note: C++ does not support default-int
```

The second bug is located at: `ITK_DISALLOW_COPY_AND_MOVE(FastGrowCut);` (itkFastGrowCut).

Then, I re-compile the ITK, and turn the `Build_Testing` on, and more bugs are reported:

```
1. can not open `itkImageRegionIterator.h`
2. can not open `itkImageRegionIteratorWithIndex.h`
3. can not open `itkNumericTraits.h`
4. can not open `itkRegionOfInterestImageFilter.h`
5. can not open `GrowCutExport.h`
6. can not open `itkImageToImageFilter.h`
7. can not open `itkPrintHelper.h`
8. identifier 'LabPixelType` is not defined.
9. identifier `SrcPixelType` is not defined
...
```

All the above bugs is reported from `GrowCut-all` project. 

My environment is:
```
win 10
vs 2019
cmake 3.20.4
ITK: 4.13.3
```

**Comment by dzenanz** [comment]
This remote module requires ITKv5.
