### ISSUE TITLE
Question about GrowCut

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITKGrowCut#8]
I have successful run the `ITKGrowCut` with the provided [data](https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/6081794d2fa25629b90b3687), and the result is good. 

Then, I test the `ITKGrowCut` with my own data, and the result is:

![image](https://user-images.githubusercontent.com/29271051/128282622-44caf2fa-a5e8-4887-bc62-6a044fb7f69c.png)

The shown figure is: original image (left), seed point for object and background (middle), and result from grow cut (right). 

The zoom in seed point and grow cut result is:

![image](https://user-images.githubusercontent.com/29271051/128283307-de784a79-8d25-4186-95b3-dcbf79359b1a.png)

We can see that the grow cut result is poor, which just copy the seed point. 

In the provided demo [data](https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/6081794d2fa25629b90b3687), many seeds is provided. But in my data, I only provide very few seed point, where pixel of 1 indicates ventricle and pixel of 2 indicates the background. Is the poor grow cut result caused by the few seed points?

**Comment by dzenanz** [comment]
If you provide the full image and seeds, I could check it. Alternatively, you could crop your image just to the heart region, because your initialization is only provided there. Cropped images are much smaller. Also please enable compression when saving them.

The initialization you provide should work, at least to some degree. Did you forget to call `filter->Update();`?

**Comment by zhang-qiang-github** [comment]
@dzenanz, I have uploaded my data in [github](https://github.com/zhang-qiang-github/growcut_data), and it also included my code. I do not forget to call `filter->Update()`. 

Have ITK implement the [geodesic segmentation method](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/Criminisi_eccv2008.pdf)? Github provide a [GeodisTK](https://github.com/taigw/GeodisTK), and I have tried it, the result is good:

![image](https://user-images.githubusercontent.com/29271051/128446566-dc99ba22-9653-40fb-8329-522ef9d85e12.png)

The more clear original image is:

![image](https://user-images.githubusercontent.com/29271051/128448584-ae92153e-ea11-461a-bebf-4ac8dd7a313a.png)

But it cost about 40s in my computer. Hope ITK can implement it and speed it up.

**Comment by dzenanz** [comment]
Thanks for reporting this. PR #9 fixes this for me. Can you confirm?

**Comment by zhang-qiang-github** [comment]
@dzenanz Yes, the segmentation result is OK. In addition, as [mentioned ](https://github.com/InsightSoftwareConsortium/ITKGrowCut/issues/3)by @lassoan: 


In Slicer, we significantly improved speed, robustness, memory usage and added a very important feature: masking (so that you can restrict segmentation with a binary mask), and an occasionally useful feature: **seed locality** (adding a distance penalty term to make segmentation results more consistent in images that contain very-low-noise regions).

The `Slicer` has an feature: seed locality:
![image](https://user-images.githubusercontent.com/29271051/128665310-68658eca-5bf5-4348-99e6-4292855ca9a2.png)

But this ITK module do not include this feature. Could you please implement this feature in ITK module?

**Comment by dzenanz** [comment]
> Could you please implement this feature in ITK module?

Yes, I plan to (see #3) sometime this month.
